Feature/aad integration
tw3lveparsecs/tk-421 pull request #80
Opened 2021-11-08 05:51 UTC by ThorSchutze

Created:
- aad.yml gh action - pipeline to create aks groups and users
- create-aksgroups.sh - shell script to create groups using json files as input params
- create-aksusers.sh - shell script to create users using a json file as input param

2021-11-09 10:19 UTC, tw3lveparsecs requested changes

2021-11-09 10:19 UTC, tw3lveparsecs commented on .github/workflows/aad.yml
> +    branches: [ feature/aad-integration ]
update branch to main

2021-11-09 10:19 UTC, tw3lveparsecs commented on .github/workflows/aad.yml
> +          creds: ${{ secrets.THOR_AZURE_CREDENTIALS }}
update to ${{ secrets.ENTER_SECRET_NAME }}

2021-11-09 10:19 UTC, tw3lveparsecs commented on scripts/create-aksusers.sh
> + # .github/variables/keyvault/keyvault.json
can we clean up unused code that is commented out

2021-11-15 02:56 UTC, tw3lveparsecs requested changes
looks good,  still looks like there is some leftover unused code.

2021-11-15 02:56 UTC, tw3lveparsecs commented on scripts/create-aksusers.sh
> +# for row in $(jq -c -r '(.users | .[])' .github/variables/aad/aad.json); do
can this be removed if its not needed?

2021-11-15 02:56 UTC, tw3lveparsecs commented on scripts/create-aksusers.sh
> +      # echo "Number $i"
can this be removed if its not needed?

2021-11-15 03:04 UTC, ThorSchutze commented on scripts/create-aksusers.sh
> +      # echo "Number $i"
thought I removed that

2021-11-15 05:03 UTC, tw3lveparsecs approved these changes

2021-11-15 05:03 UTC, merged